### ISSUE TITLE
Add LEO (UNUS SED LEO)

### ISSUE THREAD

**Issue by abrkn** [sideshift/cryptocurrency-icons#1]
Currency name: UNUS SED LEO
Symbol: LEO
Website: https://www.bitfinex.com/wp-2019-05.pdf
Theme color: TBD
Logo (SVG): TBD

**Comment by nonn069** [comment]
Hi:
I've just done this project, is that what you demanded?
I wait for an answer.
Thanks.

[leo.svg.zip](https://github.com/sideshift/cryptocurrency-icons/files/3276046/leo.svg.zip)

**Comment by abrkn** [comment]
Looks good.

**Comment by abrkn** [comment]
@nonn069 See https://www.bountysource.com/issues/75340095-add-leo-unus-sed-leo if you can claim the bounty

**Comment by nonn069** [comment]
i can try :), done, request sent

**Comment by nonn069** [comment]
waiting for your confirmation on bountysource
